<a href="https://colab.research.google.com/github/urness/CS167Fall2025/blob/main/Day19_MLP_in_PyTorch_Part2_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day19
## Building a Simple MLP using PyTorch Library

#### CS167: Machine Learning, Fall 2025


# Introduction to PyTorch

We can use PyTorch Framework to build and train MLPs and other neural networks such as CNN, RNN, Transformers. Let's learn the basics of PyTorch.

In [15]:
# import torch library
import torch
import torch.nn as nn
import numpy as np

## __Put the Model on Training Device (GPU or CPU)__
We want to accelerate the training process using graphical processing unit (GPU). Fortunately, in Colab we can access for GPU. You need to enable it from _Runtime-->Change runtime type-->GPU or TPU_

In [ ]:
# check to see if torch.cuda is available, otherwise it will use CPU
import torch
import torch.nn as nn
import numpy as np
device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)
print(f"Using {device} device")
# if it prints 'cuda' then colab is running using GPU device

Using cpu device


#__Group activity__
Make another simple MLP with the specifications below and perform the 'Forward Pass' of the MLP.

In [16]:
# let's generate 1 random samples of (x1, x2, x3) for the network
torch.manual_seed(0)                      # for reproducibility
random_X = torch.randn(1,3)

In [17]:
torch.manual_seed(0) # for reproducibility
# Q1: how many hidden layers should be there? (depth)
# answer: there is only 1 hidden layer
num_of_hidden_layer = 1


# Q2: how many neurons should be in each layer? (width)
# answer: there are 3 neurons in the input  layer
#         there are 4 neurons in the hidden layer
#         there are 1 neurons in the output layer
num_of_neurons_input_layer  =
num_of_neurons_hidden_layer =
num_of_neurons_output_layer =


# Q3 how many dense connections should be there in between each adjacent layers
# answer: there should be ?x? dense connnections (between input  layer and hidden layer: dense_connections_W1)
#         there should be ?x1 dense connnections (between hidden layer and output layer: dense_connections_W2)
# add the bias terms for all the layers except input layer


# Q4: what should the activation be at each of the intermediate layers?
# answer: let use sigmoid() activation function in the hidden layer

# Q5: what should be activation of the final layer (let's assume we are using a binary classification task for which sigmoid activation is used)


SyntaxError: invalid syntax (ipython-input-3173836288.py, line 11)

In [ ]:
# do the Forward Pass in Multilayer Perceptron (MLP)
# Step 1 -- input to hidden layer


# Step 2 -- hidden to output layer

In [18]:
# delete for student

torch.manual_seed(0) # for reproducibility
# Q1: how many hidden layers should be there? (depth)
# answer: there is only 1 hidden layer
num_of_hidden_layer = 1


# Q2: how many neurons should be in each layer? (width)
# answer: there are 3 neurons in the input  layer
#         there are 4 neurons in the hidden layer
#         there are 1 neurons in the output layer
num_of_neurons_input_layer  = 3
num_of_neurons_hidden_layer = 4
num_of_neurons_output_layer = 1


# Q3 how many dense connections should be there in between each adjacent layers
# answer: there should be 3x4 dense connnections (between input  layer and hidden layer: dense_connections_W1)
#         there should be 4x1 dense connnections (between hidden layer and output layer: dense_connections_W2)
dense_connections_W1 = torch.rand(num_of_neurons_input_layer, num_of_neurons_hidden_layer)
dense_connections_W2 = torch.rand(num_of_neurons_hidden_layer, num_of_neurons_output_layer)
# add the bias terms for all the layers except input layer
bias_terms_hidden = torch.rand(num_of_neurons_hidden_layer)
bias_terms_output = torch.rand(num_of_neurons_output_layer)

# Q4: what should the activation be at each of the intermediate layers?
# answer: let use sigmoid() activation function in the hidden layer
sigmoid_activation_hidden = nn.Sigmoid()

# Q5: what should be activation of the final layer (let's assume we are using a binary classification task for which sigmoid activation is used)
sigmoid_activation_output = nn.Sigmoid()


In [19]:
# do a Forward Pass in Multilayer Perceptron (MLP)

# Step 1 -- input to hidden layer
matrix_mult_X_and_W1 = torch.matmul(random_X[0,:], dense_connections_W1) + bias_terms_hidden
output_hidden_layer = sigmoid_activation_hidden(matrix_mult_X_and_W1)

# Step 2 -- hidden to output layer
matrix_mult_hidden_and_W2 = torch.matmul(output_hidden_layer, dense_connections_W2) + bias_terms_output
final_output = sigmoid_activation_output(matrix_mult_hidden_and_W2)

print('output of final layer: \n', final_output.numpy())

output of final layer: 
 [0.74611795]




---



# Creating Linear Layers using PyTorch

## **Let's build a linear layer**

In [ ]:
torch.manual_seed(2)                    # for reproducibility
# construction of a linear layer
input_layer_1 = nn.Linear(2, 4)

##**Inspecting the weights of a linear layer**

In [ ]:
# Print the weights of the linear layer
print(f'Weights: \n{input_layer_1.weight.data}')

# Print the biases of the linear layer (if they exist)
print(f'Biases: \n{input_layer_1.bias.data}')

Weights: 
tensor([[ 0.1622, -0.1683],
        [ 0.1939, -0.0361],
        [ 0.3021,  0.1683],
        [-0.0813, -0.5717]])
Biases: 
tensor([ 0.1614, -0.6260,  0.0929,  0.0470])


## **Let's generate a random input for our linear layer and plug it into our layer**

In [ ]:
# Step 1: let's generate 1 random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples     = 1
random_input          = torch.randn(number_of_samples, 2)
print(f'input numbers: \n{random_input.numpy()}\n')

# Step 2: apply forward pass through the network
output = input_layer_1(random_input)
print(f'output layer value: \n{output.data.numpy()}\n')


input numbers: 
[[ 0.39229682 -0.22356401]]

output layer value: 
[[ 0.26269433 -0.5418887   0.17379826  0.14291514]]



##**Challenge #1**
Create a new Linear layer with the following structure:

> The first layer has 2 input nodes and 16 output nodes.


In [ ]:
torch.manual_seed(2)                    # for reproducibility
# construction of a linear layer
# your code here

In [ ]:
torch.manual_seed(2)                    # for reproducibility
# construction of a linear layer
input_layer_1 = nn.Linear(2, 16)

##**Challenge #2**

> generate a random input for our linear layer and apply forward pass through the network. Print out the resulting output layer values. How many numbers do you expect?

In [ ]:
torch.manual_seed(0) # for reproducibility
# your code here

In [ ]:
torch.manual_seed(0) # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples     = 1
random_input = torch.randn(number_of_samples, 2)
print(f'input numbers: \n{random_input.numpy()}\n')

output = input_layer_1(random_input)
print(f'output layer value: \n{output.data.numpy()}\n')

input numbers: 
[[ 1.5409961 -0.2934289]]

output layer value: 
[[ 0.46574774  0.7747904   0.45092157 -0.28162462  0.7432405  -0.1420176
  -0.56590974 -0.40096116  0.36150265 -1.2736461  -0.751479    0.04142258
  -0.01777191  0.41104984 -0.21710443 -0.8239027 ]]



# Part 2

# **Let's add an activation function such as *ReLu(), tanh(), or sigmoid()* after your linear layer and run the experiment again to see how it changes the outputs.**

In [ ]:
# construction of a linear layer
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

input_linear_layer = nn.Linear(2, 4)  # linear transformation module (input=2, output=4)

# Step 1: let's generate some random samples of (x1, x2) for the above linear network
number_of_samples = 1
random_X = torch.randn(number_of_samples, 2)
print('input numbers:')
print(random_X.numpy())

sigmoid_activation = nn.Sigmoid() #this is like a call to a constructor
tanh_activation = nn.Tanh()
relu_activation  = nn.ReLU()

input numbers:
[[0.57310677 0.54094744]]


# **Sigmoid()**

In [ ]:
# Step 2: apply forward pass through the network
output = input_linear_layer(random_X)
print('output layer value: ')
print(output.data.numpy())

output_after_activation = sigmoid_activation(output) ## apply the activation function!
print('Sigmoid activation value: ')
print(output_after_activation.data.numpy())

output layer value: 
[[ 0.1633755  -0.5344403   0.3571151  -0.30882734]]
Sigmoid activation value: 
[[0.54075325 0.36948186 0.5883419  0.42340097]]


# **Exercise #4a : apply the Tanh() activation functions to the above network**

# **Exercise #4b : apply the ReLU() activation function to the above network**

Which activation function gives the result of all non-negative values?


In [ ]:
# Tanh()
output = input_linear_layer(random_X)
output_after_activation = tanh_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('Tanh activation value: ')
print(output_after_activation.data.numpy())



output layer value: 
[[ 0.1633755  -0.5344403   0.3571151  -0.30882734]]
Tanh activation value: 
[[ 0.16193727 -0.48876795  0.3426704  -0.2993699 ]]


In [ ]:
# relu()
output = input_linear_layer(random_X)
output_after_activation = tanh_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('ReLU activation value: ')
print(output_after_activation.data.numpy())

output layer value: 
[[ 0.1633755  -0.5344403   0.3571151  -0.30882734]]
ReLU activation value: 
[[ 0.16193727 -0.48876795  0.3426704  -0.2993699 ]]


In [ ]:
# ReLU()
output = input_linear_layer(random_X)
output_after_activation = relu_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('Sigmoid activation value: ')
print(output_after_activation.data.numpy())

output layer value: 
[[ 0.26269433 -0.5418887   0.17379826  0.14291514]]
Sigmoid activation value: 
[[0.26269433 0.         0.17379826 0.14291514]]


## **Let's build the simple 1-hidden layer feedforward neural network!**

<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/mlp_toy_examle_wo_weights.png" width=400/>
</div>


In [ ]:
# let's make the simple 1-Hidden layer feedforwrd neural network from the lecture slides
# only with ReLU activation for hidden layer, and no (linear) activation for output layer

torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

# construction
input_linear_layer  = nn.Linear(2, 3) # linear tranformation (input 2, output=1)
relu_activation  = nn.ReLU()
output_linear_layer = nn.Linear(3, 1) # linear transformation module (input=3, output=1)


## **We can apply a tensor through the Linear layers now**

In [ ]:
# let's generate 2 random samples of (x1, x2) for the above linear network
torch.manual_seed(2)
number_of_samples = 1
random_X = torch.randn(number_of_samples, 2) # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())

input numbers:
[[ 0.39229682 -0.22356401]]


In [ ]:
# apply forward pass through the network
hidden_layer_output = input_linear_layer(random_X)
hidden_layer_output_relu = relu_activation(hidden_layer_output)
output = output_linear_layer(hidden_layer_output_relu)
print('Output layer result: ', output.data)

Output layer result:  tensor([[-0.1279]])


# Introducing ... nn.Sequential

In [ ]:
# creation of our network
torch.manual_seed(2)
my_first_mlp = nn.Sequential(
                nn.Linear(2, 3),
                nn.ReLU(),
                nn.Linear(3, 1)
)

In [ ]:
# forward pass step
torch.manual_seed(2)
rand_input = random_X
output = my_first_mlp(rand_input)
print('final output: ', output.data)

final output:  tensor([[-0.1279]])


#**Exercise#5**
Create three Linear layers and connect them in sequence to build an MLP with the following structure:

> The first layer has 2 input nodes and 3 output nodes.

> The second layer takes 3 input nodes and outputs 6 nodes.

> The final layer connects 6 input nodes to 1 output node.

> The activation functions should be Sigmoid for each layer (including the final layer)

> Put all of your code in a single CoLab cell. Start the code with `torch.manual_seed(2)`

> Execute a forward pass step with the initial values; `input_x = torch.tensor( [[-0.5,0.5]] )`

In [ ]:
torch.manual_seed(2)
my_first_mlp = nn.Sequential(
                nn.Linear(2, 3),
                nn.Sigmoid(),
                nn.Linear(3, 6),
                nn.Sigmoid(),
                nn.Linear(6, 1),
                nn.Sigmoid()
)

input_x = torch.tensor( [[-0.5,0.5]] )
output = my_first_mlp(input_x)
print('final output: ', output.data)


final output:  tensor([[0.4365]])
